In [ ]:
import pandas as pd
import streamlit as st
from pyspark_jobs.common.config_loader import load_all_environment_configs, load_all_gold_configs
from pyspark_jobs.common.io_utils import resolve_path

env_configs, _ = load_all_environment_configs()
env_config = next(c for c in env_configs.values() if c.env == "local")

gold_configs, _ = load_all_gold_configs()
gold_config = gold_configs["readmission_vs_staffing.yaml"]

path = resolve_path(env_config, gold_config.output_path.format(env=env_config.env))
df = pd.read_parquet(path)

#df.head(10)


# Filter out any rows where readmission_rssr_upper_ci - readmission_rssr_lower_ci is greater than 6
#ci_width = df["readmission_rsrr_upper_ci"] - df["readmission_rsrr_lower_ci"]
#reliable_df = df[ci_width < 8]

#print(len(reliable_df))
#print(len(df))
#return a count of how many rows are in the dataframe
#print(f"Number of rows in the dataframe: {len(df1)}")

Index(['ccn', 'measurement_period', 'start_date', 'end_date',
       'readmission_number', 'readmission_volume', 'readmission_obs_rate',
       'readmission_rsrr', 'readmission_rsrr_lower_ci',
       'readmission_rsrr_upper_ci', 'readmission_comp_perf',
       'readmission_national_unadjusted_avg', 'avg_daily_rn_hours',
       'avg_weekday_rn_hours', 'avg_weekend_rn_hours',
       'avg_weekday_rn_staff_hours', 'avg_weekend_rn_staff_hours',
       'avg_weekday_rn_admin_hours', 'avg_weekend_rn_admin_hours',
       'avg_weekday_rn_director_of_nursing_hours',
       'avg_weekend_rn_director_of_nursing_hours', 'avg_daily_lpn_hours',
       'avg_weekday_lpn_hours', 'avg_weekend_lpn_hours',
       'avg_weekday_lpn_staff_hours', 'avg_weekend_lpn_staff_hours',
       'avg_weekday_lpn_admin_hours', 'avg_weekend_lpn_admin_hours',
       'avg_daily_cna_hours', 'avg_weekday_cna_hours', 'avg_weekend_cna_hours',
       'avg_daily_na_trainee_hours', 'avg_weekday_na_trainee_hours',
       'avg_weekend_na_trainee_hours', 'avg_daily_med_aide_hours',
       'avg_weekday_med_aide_hours', 'avg_weekend_med_aide_hours',
       'avg_daily_total_nurse_hours', 'avg_weekday_total_nurse_hours',
       'avg_weekend_total_nurse_hours', 'avg_daily_census',
       'avg_weekday_census', 'avg_weekend_census', 'rn_hours_per_resident_day',
       'rn_hours_per_resident_day_weekday',
       'rn_hours_per_resident_day_weekend', 'lpn_hours_per_resident_day',
       'lpn_hours_per_resident_day_weekday',
       'lpn_hours_per_resident_day_weekend', 'cna_hours_per_resident_day',
       'cna_hours_per_resident_day_weekday',
       'cna_hours_per_resident_day_weekend',
       'na_trainee_hours_per_resident_day',
       'na_trainee_hours_per_resident_day_weekday',
       'na_trainee_hours_per_resident_day_weekend',
       'med_aide_hours_per_resident_day',
       'med_aide_hours_per_resident_day_weekday',
       'med_aide_hours_per_resident_day_weekend',
       'total_nurse_hours_per_resident_day',
       'total_nurse_hours_per_resident_day_weekday',
       'total_nurse_hours_per_resident_day_weekend',
       'staffing_quarters_matched', 'staffing_quarters_expected',
       'national_rn_hours_per_resident_day',
       'national_lpn_hours_per_resident_day',
       'national_total_nurse_hours_per_resident_day',
       'national_total_nursing_staff_turnover', 'national_rn_turnover'],
      dtype='object')

In [8]:
import pandas as pd
from pyspark_jobs.common.config_loader import load_all_environment_configs, load_all_gold_configs
from pyspark_jobs.common.io_utils import resolve_path

env_configs, _ = load_all_environment_configs()
env_config = next(c for c in env_configs.values() if c.env == "local")

gold_configs, _ = load_all_gold_configs()
gold_config = gold_configs["dtc_vs_staffing.yaml"]

path = resolve_path(env_config, gold_config.output_path.format(env=env_config.env))
df = pd.read_parquet(path)

df.head(10)

,ccn,measurement_period,start_date,end_date,dtc_number,dtc_volume,dtc_obs_rate,dtc_rs_rate,dtc_rs_rate_lower_ci,dtc_rs_rate_upper_ci,...,total_nurse_hours_per_resident_day,total_nurse_hours_per_resident_day_weekday,total_nurse_hours_per_resident_day_weekend,staffing_quarters_matched,staffing_quarters_expected,national_rn_hours_per_resident_day,national_lpn_hours_per_resident_day,national_total_nurse_hours_per_resident_day,national_total_nursing_staff_turnover,national_rn_turnover
0,015133,2023Q3,10/01/2021,09/30/2023,42.0,99.0,42.42,51.75,41.37,61.99,...,3.248843,3.419861,2.820690,8,8,0.66807,0.88,3.83737,48.8,45.5
1,015193,2023Q3,10/01/2021,09/30/2023,36.0,74.0,48.65,58.78,47.87,71.17,...,4.409526,4.736689,3.595086,8,8,0.66807,0.88,3.83737,48.8,45.5
2,015214,2023Q3,10/01/2021,09/30/2023,10.0,31.0,32.26,40.21,27.24,56.14,...,3.886965,4.263436,2.947848,8,8,0.66807,0.88,3.83737,48.8,45.5
3,015321,2023Q3,10/01/2021,09/30/2023,11.0,39.0,28.21,39.01,26.87,53.67,...,2.432493,2.573178,2.079102,6,8,0.66807,0.88,3.83737,48.8,45.5
4,015391,2023Q3,10/01/2021,09/30/2023,89.0,203.0,43.84,48.90,41.70,55.72,...,3.201880,3.476039,2.513248,7,8,0.66807,0.88,3.83737,48.8,45.5
5,035095,2023Q3,10/01/2021,09/30/2023,43.0,73.0,58.90,61.47,50.28,72.43,...,3.569018,3.797345,2.993653,8,8,0.66807,0.88,3.83737,48.8,45.5
6,035193,2023Q3,10/01/2021,09/30/2023,17.0,46.0,36.96,48.54,35.57,63.24,...,4.012907,4.179613,3.597304,8,8,0.66807,0.88,3.83737,48.8,45.5
7,035280,2023Q3,10/01/2021,09/30/2023,504.0,747.0,67.47,69.04,65.63,72.22,...,5.276118,5.663434,4.313054,8,8,0.66807,0.88,3.83737,48.8,45.5
8,045070,2023Q3,10/01/2021,09/30/2023,25.0,81.0,30.86,37.90,28.23,48.47,...,3.199351,3.435249,2.609088,8,8,0.66807,0.88,3.83737,48.8,45.5
9,045183,2023Q3,10/01/2021,09/30/2023,77.0,149.0,51.68,56.49,47.97,64.08,...,3.958624,4.130752,3.528531,8,8,0.66807,0.88,3.83737,48.8,45.5

In [ ]:
import pandas as pd
from pyspark_jobs.common.config_loader import load_all_environment_configs, load_all_gold_configs
from pyspark_jobs.common.io_utils import resolve_path

env_configs, _ = load_all_environment_configs()
env_config = next(c for c in env_configs.values() if c.env == "local")

gold_configs, _ = load_all_gold_configs()
gold_config = gold_configs["falls_vs_staffing.yaml"]

path = resolve_path(env_config, gold_config.output_path.format(env=env_config.env))
df = pd.read_parquet(path)


df[["ccn", "measurement_period", "rn_hours_per_resident_day"]].head(10)

#df.head(10)

KeyError: "['dtc_rs_rate'] not in index"

In [10]:
import pandas as pd
from pyspark_jobs.common.config_loader import load_all_environment_configs, load_all_gold_configs
from pyspark_jobs.common.io_utils import resolve_path

env_configs, _ = load_all_environment_configs()
env_config = next(c for c in env_configs.values() if c.env == "local")

gold_configs, _ = load_all_gold_configs()
gold_config = gold_configs["hai_vs_staffing.yaml"]

path = resolve_path(env_config, gold_config.output_path.format(env=env_config.env))
df = pd.read_parquet(path)

df.head(10)

,ccn,measurement_period,start_date,end_date,hai_number,hai_volume,hai_obs_rate,hai_rs_rate,hai_rs_rate_lower_ci,hai_rs_rate_upper_ci,...,total_nurse_hours_per_resident_day,total_nurse_hours_per_resident_day_weekday,total_nurse_hours_per_resident_day_weekend,staffing_quarters_matched,staffing_quarters_expected,national_rn_hours_per_resident_day,national_lpn_hours_per_resident_day,national_total_nurse_hours_per_resident_day,national_total_nursing_staff_turnover,national_rn_turnover
0,015063,2023Q3,10/01/2022,09/30/2023,3.0,79.0,3.80,6.27,3.66,10.17,...,3.046861,3.200078,2.665293,4,4,0.66807,0.88,3.83737,48.8,45.5
1,015067,2023Q3,10/01/2022,09/30/2023,5.0,96.0,5.21,6.51,3.91,10.58,...,3.027003,3.254286,2.461225,4,4,0.66807,0.88,3.83737,48.8,45.5
2,015196,2023Q3,10/01/2022,09/30/2023,3.0,37.0,8.11,7.09,4.24,11.80,...,3.071019,3.201796,2.746233,4,4,0.66807,0.88,3.83737,48.8,45.5
3,015414,2023Q3,10/01/2022,09/30/2023,NaN,10.0,NaN,NaN,NaN,NaN,...,2.237748,2.721067,1.039624,4,4,0.66807,0.88,3.83737,48.8,45.5
4,015420,2023Q3,10/01/2022,09/30/2023,3.0,66.0,4.55,6.41,3.80,11.03,...,4.081790,4.372203,3.357426,4,4,0.66807,0.88,3.83737,48.8,45.5
5,015422,2023Q3,10/01/2022,09/30/2023,7.0,101.0,6.93,6.81,4.17,10.68,...,3.794408,3.905835,3.515859,4,4,0.66807,0.88,3.83737,48.8,45.5
6,015426,2023Q3,10/01/2022,09/30/2023,5.0,144.0,3.47,5.70,3.50,8.80,...,4.777397,5.107773,3.949140,4,4,0.66807,0.88,3.83737,48.8,45.5
7,025025,2023Q3,10/01/2022,09/30/2023,7.0,143.0,4.90,5.76,3.62,8.82,...,5.040156,5.193754,4.656837,4,4,0.66807,0.88,3.83737,48.8,45.5
8,035014,2023Q3,10/01/2022,09/30/2023,2.0,57.0,3.51,6.07,3.49,9.85,...,3.108467,3.371657,2.453035,4,4,0.66807,0.88,3.83737,48.8,45.5
9,035087,2023Q3,10/01/2022,09/30/2023,NaN,22.0,NaN,NaN,NaN,NaN,...,6.383759,6.822668,5.295202,4,4,0.66807,0.88,3.83737,48.8,45.5

In [11]:
import pandas as pd
from pyspark_jobs.common.config_loader import load_all_environment_configs, load_all_gold_configs
from pyspark_jobs.common.io_utils import resolve_path

env_configs, _ = load_all_environment_configs()
env_config = next(c for c in env_configs.values() if c.env == "local")

gold_configs, _ = load_all_gold_configs()
gold_config = gold_configs["pressure_ulcer_vs_staffing.yaml"]

path = resolve_path(env_config, gold_config.output_path.format(env=env_config.env))
df = pd.read_parquet(path)

df.head(10)

,ccn,measurement_period,start_date,end_date,pressure_ulcer_numerator,pressure_ulcer_denominator,pressure_ulcer_obs_rate,pressure_ulcer_adj_rate,pressure_ulcer_national_obs_rate,avg_daily_rn_hours,...,total_nurse_hours_per_resident_day,total_nurse_hours_per_resident_day_weekday,total_nurse_hours_per_resident_day_weekend,staffing_quarters_matched,staffing_quarters_expected,national_rn_hours_per_resident_day,national_lpn_hours_per_resident_day,national_total_nurse_hours_per_resident_day,national_total_nursing_staff_turnover,national_rn_turnover
0,015019,2023Q4,01/01/2023,12/31/2023,2.0,48.0,4.2,3.7,2.4,53.404092,...,2.998125,3.132362,2.664581,4,4,0.66807,0.88,3.83737,48.8,45.5
1,015035,2023Q4,01/01/2023,12/31/2023,6.0,66.0,9.1,7.4,2.4,56.355513,...,4.438277,4.801094,3.538224,4,4,0.66807,0.88,3.83737,48.8,45.5
2,015163,2023Q4,01/01/2023,12/31/2023,1.0,183.0,0.5,0.4,2.4,109.251407,...,4.417576,4.620362,3.911545,4,4,0.66807,0.88,3.83737,48.8,45.5
3,015166,2023Q4,01/01/2023,12/31/2023,0.0,28.0,0.0,0.0,2.4,59.224264,...,3.860646,4.075209,3.325691,4,4,0.66807,0.88,3.83737,48.8,45.5
4,015176,2023Q4,01/01/2023,12/31/2023,0.0,53.0,0.0,0.0,2.4,53.628920,...,2.998785,3.204109,2.488804,4,4,0.66807,0.88,3.83737,48.8,45.5
5,015194,2023Q4,01/01/2023,12/31/2023,0.0,112.0,0.0,0.0,2.4,43.714259,...,4.423148,4.676508,3.795135,4,4,0.66807,0.88,3.83737,48.8,45.5
6,015217,2023Q4,01/01/2023,12/31/2023,0.0,61.0,0.0,0.0,2.4,34.408774,...,3.093370,3.293238,2.599416,4,4,0.66807,0.88,3.83737,48.8,45.5
7,015222,2023Q4,01/01/2023,12/31/2023,3.0,90.0,3.3,4.2,2.4,26.670346,...,3.523412,3.752035,2.952538,4,4,0.66807,0.88,3.83737,48.8,45.5
8,015425,2023Q4,01/01/2023,12/31/2023,4.0,202.0,2.0,2.0,2.4,68.444001,...,3.587696,3.917510,2.760839,4,4,0.66807,0.88,3.83737,48.8,45.5
9,015452,2023Q4,01/01/2023,12/31/2023,1.0,26.0,3.8,3.8,2.4,38.491921,...,2.899459,3.104213,2.385019,4,4,0.66807,0.88,3.83737,48.8,45.5

In [33]:
import pandas as pd
from pyspark_jobs.common.config_loader import load_all_environment_configs, load_all_gold_configs
from pyspark_jobs.common.io_utils import resolve_path

env_configs, _ = load_all_environment_configs()
env_config = next(c for c in env_configs.values() if c.env == "dev")

gold_configs, _ = load_all_gold_configs()
gold_config = gold_configs["facility_staffing_by_quarter.yaml"]

path = resolve_path(env_config, gold_config.output_path.format(env=env_config.env))
df = pd.read_parquet(path)

df.head(10)

ImportError: Install s3fs to access S3

In [32]:
import pandas as pd
from pyspark_jobs.common.config_loader import load_all_environment_configs, load_all_gold_configs
from pyspark_jobs.common.io_utils import resolve_path

env_configs, _ = load_all_environment_configs()
env_config = next(c for c in env_configs.values() if c.env == "dev")

gold_configs, _ = load_all_gold_configs()
gold_config = gold_configs["falls_vs_staffing.yaml"]

path = resolve_path(env_config, gold_config.output_path.format(env=env_config.env))
df = pd.read_parquet(path)

df.head(10)

ImportError: Install s3fs to access S3